server:  
    port: 8080
    servlet: 
       session.timeout: 60000
       contextpath: /res    


logging:
    level.root: info
    level.org.springframework: info
    level.com.yc: info
    file: /tmp/yc.log




